CREATE SEQUENCE Autoincremento
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER AUTOINCREMENTO_Cliente
BEFORE INSERT ON CLIENTE
FOR EACH ROW
BEGIN
SELECT Autoincremento.NEXTVAL INTO :NEW.id FROM DUAL;
END;

CREATE SEQUENCE Autoincremento_Deporte
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER AUTOINCREMENTO_Deporte
BEFORE INSERT ON DEPORTE
FOR EACH ROW
BEGIN
SELECT Autoincremento_Deporte.NEXTVAL INTO :NEW.id FROM DUAL;
END;

CREATE SEQUENCE Autoincremento_Evento
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER AUTOINCREMENTO_Evento
BEFORE INSERT ON EVENTO
FOR EACH ROW
BEGIN
SELECT Autoincremento_Evento.NEXTVAL INTO :NEW.id FROM DUAL;
END;

CREATE SEQUENCE Autoincremento_fase
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER AUTOINCREMENTO_Fase
BEFORE INSERT ON FASE
FOR EACH ROW
BEGIN
SELECT Autoincremento_fase.NEXTVAL INTO :NEW.id FROM DUAL;
END;

CREATE SEQUENCE Autoincremento_Jornada
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER AUTOINCREMENTO_Jornada
BEFORE INSERT ON JORNADA
FOR EACH ROW
BEGIN
SELECT Autoincremento_Jornada.NEXTVAL INTO :NEW.id FROM DUAL;
END;

CREATE SEQUENCE Autoincremento_Membresia
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER AUTOINCREMENTO_Membresia
BEFORE INSERT ON MEMBRESIA
FOR EACH ROW
BEGIN
SELECT Autoincremento_Membresia.NEXTVAL INTO :NEW.id FROM DUAL;
END;

CREATE SEQUENCE Autoincremento_Membresia_t
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER AUTOINCREMENTO_Membresia_t
BEFORE INSERT ON MEMBRESIA_TEMPORADA
FOR EACH ROW
BEGIN
SELECT Autoincremento_Membresia_t.NEXTVAL INTO :NEW.id FROM DUAL;
END;

CREATE SEQUENCE Autoincremento_Prediccion
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER AUTOINCREMENTO_Prediccion
BEFORE INSERT ON PREDICCION
FOR EACH ROW
BEGIN
SELECT Autoincremento_Prediccion.NEXTVAL INTO :NEW.id FROM DUAL;
END;

CREATE SEQUENCE Autoincremento_Temporada
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER AUTOINCREMENTO__temporada
BEFORE INSERT ON TEMPORADA
FOR EACH ROW
BEGIN
SELECT Autoincremento_Temporada.NEXTVAL INTO :NEW.id FROM DUAL;
END;

CREATE SEQUENCE Autoincremento_Bitacora
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER AUTOINCREMENTO_Bitacora
BEFORE INSERT ON BITACORA
FOR EACH ROW
BEGIN
SELECT Autoincremento_Bitacora.NEXTVAL INTO :NEW.id FROM DUAL;
END;


drop TRIGGER AUTOINCREMENTO_Evento

drop SEQUENCE Autoincremento_Evento