CREATE OR REPLACE PROCEDURE Ingresar_Cliente (nombreE in VARCHAR2, apellidoE in VARCHAR2, passE in VARCHAR2, usernameE in VARCHAR2)
AS
BEGIN
            INSERT INTO CLIENTE (NOMBRE,APELLIDO, PASSWORD, USUARIO)
            VALUES (nombreE, apellidoE,passE,usernameE);
END;

CREATE OR REPLACE PROCEDURE Ingresar_Deporte (nombreE in VARCHAR2)
AS
BEGIN
        INSERT INTO DEPORTE (NOMBRE)
        VALUES (nombreE);
END;

CREATE OR REPLACE PROCEDURE Ingresar_temporada (nombre in VARCHAR2)
AS
BEGIN
        INSERT INTO TEMPORADA (NOMBRE)
        VALUES (nombre);
END;

CREATE OR REPLACE PROCEDURE Ingresar_Membresia (nombreE in VARCHAR2)
AS
BEGIN
        INSERT INTO MEMBRESIA (NOMBRE)
        VALUES (nombreE);
END;

CREATE OR REPLACE PROCEDURE Ingresar_Evento (nombreL in VARCHAR2, nombreV in VARCHAR2, resultadoL in INTEGER, resultadoV in INTEGER, fecha in VARCHAR2, deporte in VARCHAR2, jornada in VARCHAR2, temporadaE in INTEGER)
AS
BEGIN
        INSERT INTO EVENTO (NOMBRE_LOCAL, NOMBRE_VISITANTE, R_LOCAL, R_VISITANTE, FECHA, ID_DEPORTE, ID_JORNADA)
        VALUES (nombreL, 
        nombreV,
        resultadoL,
        resultadoV,
        TO_DATE(fecha, 'DD-MM-YYYY HH24:MI'),
        (select DEPORTE.ID from DEPORTE where DEPORTE.NOMBRE = deporte),
        (SELECT JORNADA.ID from JORNADA where JORNADA.NOMBRE = jornada AND JORNADA.ID_TEMPORADA = temporadaE)
        );
END;

CREATE OR REPLACE PROCEDURE Ingresar_Jornada (nombreE in VARCHAR2, fecha_i in VARCHAR2, fecha_f in VARCHAR2, temporadaE in VARCHAR2, faseE in VARCHAR2)
AS
BEGIN
        INSERT INTO JORNADA (NOMBRE, FECHA_INICIO, FECHA_FIN, ID_TEMPORADA, ID_FASE)
        VALUES (nombreE, 
        TO_DATE(fecha_i, 'DD-MM-YYYY HH24:MI'),
        TO_DATE(fecha_f, 'DD-MM-YYYY HH24:MI'),
        (SELECT TEMPORADA.ID from TEMPORADA where TEMPORADA.NOMBRE = temporadaE),
        (select FASE.ID from FASE WHERE FASE.NOMBRE = faseE)
        );
END;

select jornada.ID from Jornada, Temporada where josnada.nombre = :1 and jornada.id_temporada = temporada.id and temporada.nombre = :2

CREATE OR REPLACE PROCEDURE Ingresar_Membresia_temp (cli in VARCHAR2, mem in VARCHAR2, tempo in VARCHAR2)
AS
BEGIN
        INSERT INTO MEMBRESIA_TEMPORADA (ID_CLIENTE, ID_MEMBRESIA, ID_TEMPORADA)
        VALUES ((SELECT cliente.ID from CLIENTE where CLIENTE.USUARIO = cli), 
        (SELECT MEMBRESIA.ID from MEMBRESIA where MEMBRESIA.NOMBRE = mem),
        (SELECT TEMPORADA.ID from TEMPORADA where TEMPORADA.NOMBRE = tempo)
        );
END;

CREATE OR REPLACE PROCEDURE Ingresar_Prediccion (pre_local in INTEGER, pre_visitante in INTEGER, cli in VARCHAR2, even in INTEGER)
AS
BEGIN
        INSERT INTO PREDICCION (PUNTOD_LOCAL, PUNTOS_VISITANTE,ID_CLIENTE, ID_EVENTO)
        VALUES (pre_local, 
        pre_visitante,
        (SELECT cliente.ID from CLIENTE where CLIENTE.USUARIO = cli),
        even
        );
END;

CREATE OR REPLACE PROCEDURE RetornarEvento (nombreL in VARCHAR2, nombreV in )
AS
BEGIN
        INSERT INTO PREDICCION (PUNTOD_LOCAL, PUNTOS_VISITANTE,ID_CLIENTE, ID_EVENTO)
        VALUES (pre_local, 
        pre_visitante,
        (SELECT cliente.ID from CLIENTE where CLIENTE.NOMBRE = cli),
        even
        );
END;

--Create a new Procedure

-- Procedure definition

CREATE or REPLACE PROCEDURE Actualizar_Jornada (
nombreE in INTEGER) 
IS
BEGIN
        UPDATE JORNADA SET JORNADA.FECHA_INICIO = to_date((SELECT * FROM (SELECT TO_CHAR(FECHA,'YYYY-MM-DD HH24:MI') FROM EVENTO WHERE EVENTO.ID_JORNADA = nombreE
        ORDER BY TO_CHAR(FECHA,'YYYY-MM-DD HH24:MI') ASC)
        WHERE ROWNUM = 1), 'YYYY-MM-DD HH24:MI'),
        JORNADA.FECHA_FIN = to_date((SELECT * FROM (SELECT TO_CHAR(FECHA,'YYYY-MM-DD HH24:MI') FROM EVENTO WHERE EVENTO.ID_JORNADA = nombreE
        ORDER BY TO_CHAR(FECHA,'YYYY-MM-DD HH24:MI') DESC)
        WHERE ROWNUM = 1), 'YYYY-MM-DD HH24:MI')
        WHERE JORNADA.ID = nombreE; 
END ;


create or REPLACE PROCEDURE ACTUALIZAR_Temporada(idE in INTEGER)
IS
BEGIN
        UPDATE TEMPORADA SET TEMPORADA.FECHA_INICIO = to_date((SELECT * FROM (SELECT TO_CHAR(JORNADA.FECHA_INICIO,'YYYY-MM-DD HH24:MI') FROM JORNADA WHERE JORNADA.ID_TEMPORADA = idE
        ORDER BY TO_CHAR(JORNADA.FECHA_INICIO,'YYYY-MM-DD HH24:MI') ASC)
        WHERE ROWNUM = 1),'YYYY-MM-DD HH24:MI'),
        TEMPORADA.FECHA_FIN = to_date((SELECT * FROM (SELECT TO_CHAR(JORNADA.FECHA_FIN,'YYYY-MM-DD HH24:MI') FROM JORNADA WHERE JORNADA.ID_TEMPORADA = idE
        ORDER BY TO_CHAR(JORNADA.FECHA_FIN,'YYYY-MM-DD HH24:MI') DESC)
        WHERE ROWNUM = 1),'YYYY-MM-DD HH24:MI')
        WHERE TEMPORADA.ID = idE;
END;


CREATE or REPLACE PROCEDURE Crear_Evento(nombreL  in VARCHAR2, nombreV in VARCHAR2, fechaE VARCHAR2, idJornada in INTEGER, idDeporte in INTEGER)
IS
BEGIN
        INSERT INTO EVENTO(NOMBRE_LOCAL, NOMBRE_VISITANTE, FECHA, ID_JORNADA, ID_DEPORTE)
        VALUES(
                nombreL,
                nombreV,
                to_date(fechaE, 'DD-MM-YYYY HH24:MI'),
                idJornada,
                idDeporte
        );
END;


CREATE or REPLACE PROCEDURE Creat_Temporada(nombreE in VARCHAR2, fechai in VARCHAR2, fechaf in VARCHAR2, faseE in VARCHAR2)
IS
BEGIN
        INSERT INTO Temporada (NOMBRE, FECHA_INICIO, FECHA_FIN, FASE)
        values(nombreE,
        to_date(fechai, 'DD-MM-YYYY HH24:MI'),
        to_date(fechaf, 'DD-MM-YYYY HH24:MI'),
        (select FASE.ID from FASE WHERE FASE.NOMBRE = faseE)
        );
END;

CREATE or REPLACE PROCEDURE Crear_Jornada(nombreE in VARCHAR2, fechai in VARCHAR2, fechaf in VARCHAR2, temporadaE in INTEGER, faseE in VARCHAR2)
IS
BEGIN
        insert into JORNADA(NOMBRE, FECHA_INICIO, FECHA_FIN, ID_TEMPORADA, ID_FASE)
        VALUES(nombreE,
        to_date(fechai, 'dd/mm/yyyy hh24:mi'),
        to_date(fechaf, 'dd/mm/yyyy hh24:mi'),
        temporadaE,
        (select FASE.ID from FASE WHERE FASE.NOMBRE = faseE)
        );
END;




-----------------------------------Pruebas--------------

alter TABLE TEMPORADA
add Fase INTEGER;

select * FROM EVENTO WHERE EVENTO.ID_JORNADA = 3

SELECT * from TEMPORADA
SELECT NOMBRE_LOCAL, NOMBRE_VISITANTE, TO_CHAR(FECHA,'DD/MM/YYYY HH24:MI') FROM EVENTO

select object_type,count(*) from user_objects where status = 'INVALID' 
group by object_type;

drop PROCEDURE Ingresar_Cliente;

SELECT * from TEMPORADA;
SELECT NOMBRE_LOCAL, NOMBRE_VISITANTE, to_char(fecha,'DD/MM/YYYY HH24:MI') FROM EVENTO

SELECT ID FROM EVENTO where NOMBRE_LOCAL = 'Kermit Garbar' and NOMBRE_VISITANTE = 'Sarge Rowlings' and TO_CHAR(FECHA,'DD/MM/YYYY HH24:MI') = '05/03/2018 11:58'

SELECT jornada.NOMBRE FROM JORNADA, TEMPORADA WHERE jornada.NOMBRE = 'j1' and TEMPORADA.ID = JORNADA.ID_TEMPORADA and TEMPORADA.NOMBRE ='2019-Q2'
GROUP BY jornada.NOMBRE

SELECT NOMBRE_LOCAL FROM EVENTO WHERE NOMBRE_LOCAL = :1 and NOMBRE_VISITANTE = :2 and to_char(fecha,'DD/MM/YYYY HH24:MI') = :3

SELECT PREDICCION.ID FROM PREDICCION, CLIENTE, EVENTO WHERE CLIENTE.ID = PREDICCION.ID_CLIENTE and EVENTO.ID = PREDICCION.ID_CLIENTE and CLIENTE.USUARIO = :1 and TO_CHAR(evento.FECHA,'DD/MM/YYYY HH24:MI') = :2

DELETE FROM EVENTO;
DELETE FROM JORNADA;
DELETE FROM MEMBRESIA_TEMPORADA;
DELETE FROM PREDICCION;
DELETE FROM TEMPORADA;
DELETE FROM CLIENTE;
DELETE FROM MEMBRESIA;
DELETE FROM DEPORTE;


SELECT NOMBRE_LOCAL, NOMBRE_VISITANTE, TO_CHAR(FECHA,'DD/MM/YYYY HH24:MI') FROM EVENTO

SELECT * FROM (SELECT TO_CHAR(JORNADA.FECHA_INICIO,'YYYY-MM-DD HH24:MI') FROM JORNADA WHERE JORNADA.ID_TEMPORADA = 3
ORDER BY TO_CHAR(JORNADA.FECHA_FIN,'YYYY-MM-DD HH24:MI') DESC)
WHERE ROWNUM = 1



SELECT * FROM (SELECT TEMPORADA.ID, FASE.NOMBRE, TO_CHAR(TEMPORADA.FECHA_FIN,'YYYY-MM-DD HH24:MI') FROM TEMPORADA, FASE WHERE TEMPORADA.FASE = FASE.ID
	ORDER BY TO_CHAR(TEMPORADA.FECHA_FIN,'YYYY-MM-DD HH24:MI') DESC)
	WHERE ROWNUM = 1


SELECT * FROM (SELECT TEMPORADA.ID,  TO_CHAR(TEMPORADA.FECHA_FIN,'YYYY-MM-DD HH24:MI') FROM TEMPORADA
	ORDER BY TO_CHAR(TEMPORADA.FECHA_FIN,'YYYY-MM-DD HH24:MI') DESC)
	WHERE ROWNUM = 1

UPDATE TEMPORADA SET
TEMPORADA.FASE = 1
WHERE ID = 1


SELECT * FROM (SELECT JORNADA.ID, FASE.NOMBRE, TO_CHAR(JORNADA.FECHA_FIN,'YYYY-MM-DD HH24:MI') FROM JORNADA, FASE WHERE JORNADA.ID_FASE = FASE.ID
	ORDER BY TO_CHAR(JORNADA.FECHA_FIN,'YYYY-MM-DD HH24:MI') ASC)
	WHERE ROWNUM = 1

SELECT * FROM JORNADA


SELECT TO_CHAR(FECHA,'YYYY-MM-DD HH24:MI') FROM EVENTO
ORDER BY TO_CHAR(FECHA,'YYYY-MM-DD HH24:MI') asc

SELECT * FROM JORNADA WHERE ID = 3

SELECT * FROM TEMPORADA WHERE ID = 3

SELECT * FROM (SELECT TO_CHAR(FECHA,'YYYY-MM-DD HH24:MI') FROM EVENTO
        ORDER BY TO_CHAR(FECHA,'YYYY-MM-DD HH24:MI') ASC)
        WHERE ROWNUM = 1


SELECT * FROM (SELECT ID, TO_CHAR(JORNADA.FECHA_FIN,'YYYY-MM-DD HH24:MI') FROM JORNADA
        ORDER BY TO_CHAR(JORNADA.FECHA_FIN,'YYYY-MM-DD HH24:MI') DESC)
        WHERE ROWNUM = 1



SELECT * FROM (SELECT ID, TO_CHAR(TEMPORADA.FECHA_FIN,'YYYY-MM-DD HH24:MI') FROM TEMPORADA
        ORDER BY TO_CHAR(TEMPORADA.FECHA_FIN,'YYYY-MM-DD HH24:MI') DESC)
        WHERE ROWNUM = 1

SELECT * FROM EVENTO